/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as HeaderLayoutImport } from './app/routes/_headerLayout'
import { Route as AdminLayoutImport } from './app/routes/_adminLayout'
import { Route as HeaderLayoutIndexImport } from './app/routes/_headerLayout/index'
import { Route as HeaderLayoutAdminImport } from './app/routes/_headerLayout/admin'
import { Route as AdminLayoutAdminAnalyticImport } from './app/routes/_adminLayout/admin/analytic'
import { Route as AdminLayoutAdminNominationsIndexImport } from './app/routes/_adminLayout/admin/nominations/index'
<<<<<<< HEAD
=======
import { Route as AdminLayoutAdminTestChangeImport } from './app/routes/_adminLayout/admin/test/change'
import { Route as AdminLayoutAdminTestAddImport } from './app/routes/_adminLayout/admin/test/add'
import { Route as AdminLayoutAdminNominationsChangeImport } from './app/routes/_adminLayout/admin/nominations/change'
import { Route as AdminLayoutAdminNominationsAddImport } from './app/routes/_adminLayout/admin/nominations/add'
import { Route as AdminLayoutAdminMembersChangeImport } from './app/routes/_adminLayout/admin/members/change'
import { Route as AdminLayoutAdminMembersAddImport } from './app/routes/_adminLayout/admin/members/add'
import { Route as AdminLayoutAdminBranchChangeImport } from './app/routes/_adminLayout/admin/branch/change'
import { Route as AdminLayoutAdminBranchAddImport } from './app/routes/_adminLayout/admin/branch/add'
>>>>>>> dd883158b3fa20ac2386ded6eb338fd322a14ab4

// Create/Update Routes

const HeaderLayoutRoute = HeaderLayoutImport.update({
  id: '/_headerLayout',
  getParentRoute: () => rootRoute,
} as any)

const AdminLayoutRoute = AdminLayoutImport.update({
  id: '/_adminLayout',
  getParentRoute: () => rootRoute,
} as any)

const HeaderLayoutIndexRoute = HeaderLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeaderLayoutRoute,
} as any)

const HeaderLayoutAdminRoute = HeaderLayoutAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => HeaderLayoutRoute,
} as any)

const AdminLayoutAdminAnalyticRoute = AdminLayoutAdminAnalyticImport.update({
  id: '/admin/analytic',
  path: '/admin/analytic',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutAdminNominationsIndexRoute =
  AdminLayoutAdminNominationsIndexImport.update({
    id: '/admin/nominations/',
    path: '/admin/nominations/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

<<<<<<< HEAD
=======
const AdminLayoutAdminTestChangeRoute = AdminLayoutAdminTestChangeImport.update(
  {
    id: '/admin/test/change',
    path: '/admin/test/change',
    getParentRoute: () => AdminLayoutRoute,
  } as any,
)

const AdminLayoutAdminTestAddRoute = AdminLayoutAdminTestAddImport.update({
  id: '/admin/test/add',
  path: '/admin/test/add',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutAdminNominationsChangeRoute =
  AdminLayoutAdminNominationsChangeImport.update({
    id: '/admin/nominations/change',
    path: '/admin/nominations/change',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminNominationsAddRoute =
  AdminLayoutAdminNominationsAddImport.update({
    id: '/admin/nominations/add',
    path: '/admin/nominations/add',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminMembersChangeRoute =
  AdminLayoutAdminMembersChangeImport.update({
    id: '/admin/members/change',
    path: '/admin/members/change',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminMembersAddRoute = AdminLayoutAdminMembersAddImport.update(
  {
    id: '/admin/members/add',
    path: '/admin/members/add',
    getParentRoute: () => AdminLayoutRoute,
  } as any,
)

const AdminLayoutAdminBranchChangeRoute =
  AdminLayoutAdminBranchChangeImport.update({
    id: '/admin/branch/change',
    path: '/admin/branch/change',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminBranchAddRoute = AdminLayoutAdminBranchAddImport.update({
  id: '/admin/branch/add',
  path: '/admin/branch/add',
  getParentRoute: () => AdminLayoutRoute,
} as any)

>>>>>>> dd883158b3fa20ac2386ded6eb338fd322a14ab4
// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_adminLayout': {
      id: '/_adminLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_headerLayout': {
      id: '/_headerLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HeaderLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_headerLayout/admin': {
      id: '/_headerLayout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof HeaderLayoutAdminImport
      parentRoute: typeof HeaderLayoutImport
    }
    '/_headerLayout/': {
      id: '/_headerLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutIndexImport
      parentRoute: typeof HeaderLayoutImport
    }
    '/_adminLayout/admin/analytic': {
      id: '/_adminLayout/admin/analytic'
      path: '/admin/analytic'
      fullPath: '/admin/analytic'
      preLoaderRoute: typeof AdminLayoutAdminAnalyticImport
      parentRoute: typeof AdminLayoutImport
    }
<<<<<<< HEAD
=======
    '/_adminLayout/admin/branch/add': {
      id: '/_adminLayout/admin/branch/add'
      path: '/admin/branch/add'
      fullPath: '/admin/branch/add'
      preLoaderRoute: typeof AdminLayoutAdminBranchAddImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/branch/change': {
      id: '/_adminLayout/admin/branch/change'
      path: '/admin/branch/change'
      fullPath: '/admin/branch/change'
      preLoaderRoute: typeof AdminLayoutAdminBranchChangeImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/members/add': {
      id: '/_adminLayout/admin/members/add'
      path: '/admin/members/add'
      fullPath: '/admin/members/add'
      preLoaderRoute: typeof AdminLayoutAdminMembersAddImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/members/change': {
      id: '/_adminLayout/admin/members/change'
      path: '/admin/members/change'
      fullPath: '/admin/members/change'
      preLoaderRoute: typeof AdminLayoutAdminMembersChangeImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/nominations/add': {
      id: '/_adminLayout/admin/nominations/add'
      path: '/admin/nominations/add'
      fullPath: '/admin/nominations/add'
      preLoaderRoute: typeof AdminLayoutAdminNominationsAddImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/nominations/change': {
      id: '/_adminLayout/admin/nominations/change'
      path: '/admin/nominations/change'
      fullPath: '/admin/nominations/change'
      preLoaderRoute: typeof AdminLayoutAdminNominationsChangeImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/test/add': {
      id: '/_adminLayout/admin/test/add'
      path: '/admin/test/add'
      fullPath: '/admin/test/add'
      preLoaderRoute: typeof AdminLayoutAdminTestAddImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/test/change': {
      id: '/_adminLayout/admin/test/change'
      path: '/admin/test/change'
      fullPath: '/admin/test/change'
      preLoaderRoute: typeof AdminLayoutAdminTestChangeImport
      parentRoute: typeof AdminLayoutImport
    }
>>>>>>> dd883158b3fa20ac2386ded6eb338fd322a14ab4
    '/_adminLayout/admin/nominations/': {
      id: '/_adminLayout/admin/nominations/'
      path: '/admin/nominations'
      fullPath: '/admin/nominations'
      preLoaderRoute: typeof AdminLayoutAdminNominationsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
  }
}

// Create and export the route tree

interface AdminLayoutRouteChildren {
  AdminLayoutAdminAnalyticRoute: typeof AdminLayoutAdminAnalyticRoute
<<<<<<< HEAD
=======
  AdminLayoutAdminBranchAddRoute: typeof AdminLayoutAdminBranchAddRoute
  AdminLayoutAdminBranchChangeRoute: typeof AdminLayoutAdminBranchChangeRoute
  AdminLayoutAdminMembersAddRoute: typeof AdminLayoutAdminMembersAddRoute
  AdminLayoutAdminMembersChangeRoute: typeof AdminLayoutAdminMembersChangeRoute
  AdminLayoutAdminNominationsAddRoute: typeof AdminLayoutAdminNominationsAddRoute
  AdminLayoutAdminNominationsChangeRoute: typeof AdminLayoutAdminNominationsChangeRoute
  AdminLayoutAdminTestAddRoute: typeof AdminLayoutAdminTestAddRoute
  AdminLayoutAdminTestChangeRoute: typeof AdminLayoutAdminTestChangeRoute
>>>>>>> dd883158b3fa20ac2386ded6eb338fd322a14ab4
  AdminLayoutAdminNominationsIndexRoute: typeof AdminLayoutAdminNominationsIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAdminAnalyticRoute: AdminLayoutAdminAnalyticRoute,
<<<<<<< HEAD
=======
  AdminLayoutAdminBranchAddRoute: AdminLayoutAdminBranchAddRoute,
  AdminLayoutAdminBranchChangeRoute: AdminLayoutAdminBranchChangeRoute,
  AdminLayoutAdminMembersAddRoute: AdminLayoutAdminMembersAddRoute,
  AdminLayoutAdminMembersChangeRoute: AdminLayoutAdminMembersChangeRoute,
  AdminLayoutAdminNominationsAddRoute: AdminLayoutAdminNominationsAddRoute,
  AdminLayoutAdminNominationsChangeRoute:
    AdminLayoutAdminNominationsChangeRoute,
  AdminLayoutAdminTestAddRoute: AdminLayoutAdminTestAddRoute,
  AdminLayoutAdminTestChangeRoute: AdminLayoutAdminTestChangeRoute,
>>>>>>> dd883158b3fa20ac2386ded6eb338fd322a14ab4
  AdminLayoutAdminNominationsIndexRoute: AdminLayoutAdminNominationsIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface HeaderLayoutRouteChildren {
  HeaderLayoutAdminRoute: typeof HeaderLayoutAdminRoute
  HeaderLayoutIndexRoute: typeof HeaderLayoutIndexRoute
}

const HeaderLayoutRouteChildren: HeaderLayoutRouteChildren = {
  HeaderLayoutAdminRoute: HeaderLayoutAdminRoute,
  HeaderLayoutIndexRoute: HeaderLayoutIndexRoute,
}

const HeaderLayoutRouteWithChildren = HeaderLayoutRoute._addFileChildren(
  HeaderLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof HeaderLayoutRouteWithChildren
  '/admin': typeof HeaderLayoutAdminRoute
  '/': typeof HeaderLayoutIndexRoute
  '/admin/analytic': typeof AdminLayoutAdminAnalyticRoute
<<<<<<< HEAD
=======
  '/admin/branch/add': typeof AdminLayoutAdminBranchAddRoute
  '/admin/branch/change': typeof AdminLayoutAdminBranchChangeRoute
  '/admin/members/add': typeof AdminLayoutAdminMembersAddRoute
  '/admin/members/change': typeof AdminLayoutAdminMembersChangeRoute
  '/admin/nominations/add': typeof AdminLayoutAdminNominationsAddRoute
  '/admin/nominations/change': typeof AdminLayoutAdminNominationsChangeRoute
  '/admin/test/add': typeof AdminLayoutAdminTestAddRoute
  '/admin/test/change': typeof AdminLayoutAdminTestChangeRoute
>>>>>>> dd883158b3fa20ac2386ded6eb338fd322a14ab4
  '/admin/nominations': typeof AdminLayoutAdminNominationsIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AdminLayoutRouteWithChildren
  '/admin': typeof HeaderLayoutAdminRoute
  '/': typeof HeaderLayoutIndexRoute
  '/admin/analytic': typeof AdminLayoutAdminAnalyticRoute
<<<<<<< HEAD
=======
  '/admin/branch/add': typeof AdminLayoutAdminBranchAddRoute
  '/admin/branch/change': typeof AdminLayoutAdminBranchChangeRoute
  '/admin/members/add': typeof AdminLayoutAdminMembersAddRoute
  '/admin/members/change': typeof AdminLayoutAdminMembersChangeRoute
  '/admin/nominations/add': typeof AdminLayoutAdminNominationsAddRoute
  '/admin/nominations/change': typeof AdminLayoutAdminNominationsChangeRoute
  '/admin/test/add': typeof AdminLayoutAdminTestAddRoute
  '/admin/test/change': typeof AdminLayoutAdminTestChangeRoute
>>>>>>> dd883158b3fa20ac2386ded6eb338fd322a14ab4
  '/admin/nominations': typeof AdminLayoutAdminNominationsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_adminLayout': typeof AdminLayoutRouteWithChildren
  '/_headerLayout': typeof HeaderLayoutRouteWithChildren
  '/_headerLayout/admin': typeof HeaderLayoutAdminRoute
  '/_headerLayout/': typeof HeaderLayoutIndexRoute
  '/_adminLayout/admin/analytic': typeof AdminLayoutAdminAnalyticRoute
<<<<<<< HEAD
=======
  '/_adminLayout/admin/branch/add': typeof AdminLayoutAdminBranchAddRoute
  '/_adminLayout/admin/branch/change': typeof AdminLayoutAdminBranchChangeRoute
  '/_adminLayout/admin/members/add': typeof AdminLayoutAdminMembersAddRoute
  '/_adminLayout/admin/members/change': typeof AdminLayoutAdminMembersChangeRoute
  '/_adminLayout/admin/nominations/add': typeof AdminLayoutAdminNominationsAddRoute
  '/_adminLayout/admin/nominations/change': typeof AdminLayoutAdminNominationsChangeRoute
  '/_adminLayout/admin/test/add': typeof AdminLayoutAdminTestAddRoute
  '/_adminLayout/admin/test/change': typeof AdminLayoutAdminTestChangeRoute
>>>>>>> dd883158b3fa20ac2386ded6eb338fd322a14ab4
  '/_adminLayout/admin/nominations/': typeof AdminLayoutAdminNominationsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/'
    | '/admin/analytic'
    | '/admin/branch/add'
    | '/admin/branch/change'
    | '/admin/members/add'
    | '/admin/members/change'
    | '/admin/nominations/add'
    | '/admin/nominations/change'
    | '/admin/test/add'
    | '/admin/test/change'
    | '/admin/nominations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/admin'
    | '/'
    | '/admin/analytic'
    | '/admin/branch/add'
    | '/admin/branch/change'
    | '/admin/members/add'
    | '/admin/members/change'
    | '/admin/nominations/add'
    | '/admin/nominations/change'
    | '/admin/test/add'
    | '/admin/test/change'
    | '/admin/nominations'
  id:
    | '__root__'
    | '/_adminLayout'
    | '/_headerLayout'
    | '/_headerLayout/admin'
    | '/_headerLayout/'
    | '/_adminLayout/admin/analytic'
<<<<<<< HEAD
=======
    | '/_adminLayout/admin/branch/add'
    | '/_adminLayout/admin/branch/change'
    | '/_adminLayout/admin/members/add'
    | '/_adminLayout/admin/members/change'
    | '/_adminLayout/admin/nominations/add'
    | '/_adminLayout/admin/nominations/change'
    | '/_adminLayout/admin/test/add'
    | '/_adminLayout/admin/test/change'
>>>>>>> dd883158b3fa20ac2386ded6eb338fd322a14ab4
    | '/_adminLayout/admin/nominations/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  HeaderLayoutRoute: typeof HeaderLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  HeaderLayoutRoute: HeaderLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_adminLayout",
        "/_headerLayout"
      ]
    },
    "/_adminLayout": {
      "filePath": "_adminLayout.tsx",
      "children": [
        "/_adminLayout/admin/analytic",
<<<<<<< HEAD
=======
        "/_adminLayout/admin/branch/add",
        "/_adminLayout/admin/branch/change",
        "/_adminLayout/admin/members/add",
        "/_adminLayout/admin/members/change",
        "/_adminLayout/admin/nominations/add",
        "/_adminLayout/admin/nominations/change",
        "/_adminLayout/admin/test/add",
        "/_adminLayout/admin/test/change",
>>>>>>> dd883158b3fa20ac2386ded6eb338fd322a14ab4
        "/_adminLayout/admin/nominations/"
      ]
    },
    "/_headerLayout": {
      "filePath": "_headerLayout.tsx",
      "children": [
        "/_headerLayout/admin",
        "/_headerLayout/"
      ]
    },
    "/_headerLayout/admin": {
      "filePath": "_headerLayout/admin.tsx",
      "parent": "/_headerLayout"
    },
    "/_headerLayout/": {
      "filePath": "_headerLayout/index.tsx",
      "parent": "/_headerLayout"
    },
    "/_adminLayout/admin/analytic": {
      "filePath": "_adminLayout/admin/analytic.tsx",
      "parent": "/_adminLayout"
    },
<<<<<<< HEAD
=======
    "/_adminLayout/admin/branch/add": {
      "filePath": "_adminLayout/admin/branch/add.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/branch/change": {
      "filePath": "_adminLayout/admin/branch/change.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/members/add": {
      "filePath": "_adminLayout/admin/members/add.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/members/change": {
      "filePath": "_adminLayout/admin/members/change.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/nominations/add": {
      "filePath": "_adminLayout/admin/nominations/add.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/nominations/change": {
      "filePath": "_adminLayout/admin/nominations/change.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/test/add": {
      "filePath": "_adminLayout/admin/test/add.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/test/change": {
      "filePath": "_adminLayout/admin/test/change.tsx",
      "parent": "/_adminLayout"
    },
>>>>>>> dd883158b3fa20ac2386ded6eb338fd322a14ab4
    "/_adminLayout/admin/nominations/": {
      "filePath": "_adminLayout/admin/nominations/index.tsx",
      "parent": "/_adminLayout"
    }
  }
}
ROUTE_MANIFEST_END */
