/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as HeaderLayoutImport } from './app/routes/_headerLayout'
import { Route as AdminLayoutImport } from './app/routes/_adminLayout'
import { Route as HeaderLayoutIndexImport } from './app/routes/_headerLayout/index'
import { Route as HeaderLayoutAdminImport } from './app/routes/_headerLayout/admin'
import { Route as AdminLayoutAdminResultsImport } from './app/routes/_adminLayout/admin/results'
import { Route as AdminLayoutAdminAnalyticImport } from './app/routes/_adminLayout/admin/analytic'
import { Route as AdminLayoutAdminNominationsIndexImport } from './app/routes/_adminLayout/admin/nominations/index'
import { Route as AdminLayoutAdminMembersIndexImport } from './app/routes/_adminLayout/admin/members/index'
import { Route as AdminLayoutAdminBranchesIndexImport } from './app/routes/_adminLayout/admin/branches/index'
import { Route as AdminLayoutAdminTestChangeImport } from './app/routes/_adminLayout/admin/test/change'
import { Route as AdminLayoutAdminTestAddImport } from './app/routes/_adminLayout/admin/test/add'
import { Route as AdminLayoutAdminNominationsUpdateNominationImport } from './app/routes/_adminLayout/admin/nominations/update-nomination'
import { Route as AdminLayoutAdminNominationsCreateNominationImport } from './app/routes/_adminLayout/admin/nominations/create-nomination'
import { Route as AdminLayoutAdminMembersUpdateMemberImport } from './app/routes/_adminLayout/admin/members/update-member'
import { Route as AdminLayoutAdminMembersCreateMemberImport } from './app/routes/_adminLayout/admin/members/create-member'
import { Route as AdminLayoutAdminBranchesUpdateBranchImport } from './app/routes/_adminLayout/admin/branches/update-branch'
import { Route as AdminLayoutAdminBranchesCreateBranchImport } from './app/routes/_adminLayout/admin/branches/create-branch'

// Create/Update Routes

const HeaderLayoutRoute = HeaderLayoutImport.update({
  id: '/_headerLayout',
  getParentRoute: () => rootRoute,
} as any)

const AdminLayoutRoute = AdminLayoutImport.update({
  id: '/_adminLayout',
  getParentRoute: () => rootRoute,
} as any)

const HeaderLayoutIndexRoute = HeaderLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeaderLayoutRoute,
} as any)

const HeaderLayoutAdminRoute = HeaderLayoutAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => HeaderLayoutRoute,
} as any)

const AdminLayoutAdminResultsRoute = AdminLayoutAdminResultsImport.update({
  id: '/admin/results',
  path: '/admin/results',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutAdminAnalyticRoute = AdminLayoutAdminAnalyticImport.update({
  id: '/admin/analytic',
  path: '/admin/analytic',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutAdminNominationsIndexRoute =
  AdminLayoutAdminNominationsIndexImport.update({
    id: '/admin/nominations/',
    path: '/admin/nominations/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminMembersIndexRoute =
  AdminLayoutAdminMembersIndexImport.update({
    id: '/admin/members/',
    path: '/admin/members/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminBranchesIndexRoute =
  AdminLayoutAdminBranchesIndexImport.update({
    id: '/admin/branches/',
    path: '/admin/branches/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminTestChangeRoute = AdminLayoutAdminTestChangeImport.update(
  {
    id: '/admin/test/change',
    path: '/admin/test/change',
    getParentRoute: () => AdminLayoutRoute,
  } as any,
)

const AdminLayoutAdminTestAddRoute = AdminLayoutAdminTestAddImport.update({
  id: '/admin/test/add',
  path: '/admin/test/add',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutAdminNominationsUpdateNominationRoute =
  AdminLayoutAdminNominationsUpdateNominationImport.update({
    id: '/admin/nominations/update-nomination',
    path: '/admin/nominations/update-nomination',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminNominationsCreateNominationRoute =
  AdminLayoutAdminNominationsCreateNominationImport.update({
    id: '/admin/nominations/create-nomination',
    path: '/admin/nominations/create-nomination',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminMembersUpdateMemberRoute =
  AdminLayoutAdminMembersUpdateMemberImport.update({
    id: '/admin/members/update-member',
    path: '/admin/members/update-member',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminMembersCreateMemberRoute =
  AdminLayoutAdminMembersCreateMemberImport.update({
    id: '/admin/members/create-member',
    path: '/admin/members/create-member',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminBranchesUpdateBranchRoute =
  AdminLayoutAdminBranchesUpdateBranchImport.update({
    id: '/admin/branches/update-branch',
    path: '/admin/branches/update-branch',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminBranchesCreateBranchRoute =
  AdminLayoutAdminBranchesCreateBranchImport.update({
    id: '/admin/branches/create-branch',
    path: '/admin/branches/create-branch',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_adminLayout': {
      id: '/_adminLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_headerLayout': {
      id: '/_headerLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HeaderLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_headerLayout/admin': {
      id: '/_headerLayout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof HeaderLayoutAdminImport
      parentRoute: typeof HeaderLayoutImport
    }
    '/_headerLayout/': {
      id: '/_headerLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutIndexImport
      parentRoute: typeof HeaderLayoutImport
    }
    '/_adminLayout/admin/analytic': {
      id: '/_adminLayout/admin/analytic'
      path: '/admin/analytic'
      fullPath: '/admin/analytic'
      preLoaderRoute: typeof AdminLayoutAdminAnalyticImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/results': {
      id: '/_adminLayout/admin/results'
      path: '/admin/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminLayoutAdminResultsImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/branches/create-branch': {
      id: '/_adminLayout/admin/branches/create-branch'
      path: '/admin/branches/create-branch'
      fullPath: '/admin/branches/create-branch'
      preLoaderRoute: typeof AdminLayoutAdminBranchesCreateBranchImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/branches/update-branch': {
      id: '/_adminLayout/admin/branches/update-branch'
      path: '/admin/branches/update-branch'
      fullPath: '/admin/branches/update-branch'
      preLoaderRoute: typeof AdminLayoutAdminBranchesUpdateBranchImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/members/create-member': {
      id: '/_adminLayout/admin/members/create-member'
      path: '/admin/members/create-member'
      fullPath: '/admin/members/create-member'
      preLoaderRoute: typeof AdminLayoutAdminMembersCreateMemberImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/members/update-member': {
      id: '/_adminLayout/admin/members/update-member'
      path: '/admin/members/update-member'
      fullPath: '/admin/members/update-member'
      preLoaderRoute: typeof AdminLayoutAdminMembersUpdateMemberImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/nominations/create-nomination': {
      id: '/_adminLayout/admin/nominations/create-nomination'
      path: '/admin/nominations/create-nomination'
      fullPath: '/admin/nominations/create-nomination'
      preLoaderRoute: typeof AdminLayoutAdminNominationsCreateNominationImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/nominations/update-nomination': {
      id: '/_adminLayout/admin/nominations/update-nomination'
      path: '/admin/nominations/update-nomination'
      fullPath: '/admin/nominations/update-nomination'
      preLoaderRoute: typeof AdminLayoutAdminNominationsUpdateNominationImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/test/add': {
      id: '/_adminLayout/admin/test/add'
      path: '/admin/test/add'
      fullPath: '/admin/test/add'
      preLoaderRoute: typeof AdminLayoutAdminTestAddImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/test/change': {
      id: '/_adminLayout/admin/test/change'
      path: '/admin/test/change'
      fullPath: '/admin/test/change'
      preLoaderRoute: typeof AdminLayoutAdminTestChangeImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/branches/': {
      id: '/_adminLayout/admin/branches/'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminLayoutAdminBranchesIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/members/': {
      id: '/_adminLayout/admin/members/'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminLayoutAdminMembersIndexImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/nominations/': {
      id: '/_adminLayout/admin/nominations/'
      path: '/admin/nominations'
      fullPath: '/admin/nominations'
      preLoaderRoute: typeof AdminLayoutAdminNominationsIndexImport
      parentRoute: typeof AdminLayoutImport
    }
  }
}

// Create and export the route tree

interface AdminLayoutRouteChildren {
  AdminLayoutAdminAnalyticRoute: typeof AdminLayoutAdminAnalyticRoute
  AdminLayoutAdminResultsRoute: typeof AdminLayoutAdminResultsRoute
  AdminLayoutAdminBranchesCreateBranchRoute: typeof AdminLayoutAdminBranchesCreateBranchRoute
  AdminLayoutAdminBranchesUpdateBranchRoute: typeof AdminLayoutAdminBranchesUpdateBranchRoute
  AdminLayoutAdminMembersCreateMemberRoute: typeof AdminLayoutAdminMembersCreateMemberRoute
  AdminLayoutAdminMembersUpdateMemberRoute: typeof AdminLayoutAdminMembersUpdateMemberRoute
  AdminLayoutAdminNominationsCreateNominationRoute: typeof AdminLayoutAdminNominationsCreateNominationRoute
  AdminLayoutAdminNominationsUpdateNominationRoute: typeof AdminLayoutAdminNominationsUpdateNominationRoute
  AdminLayoutAdminTestAddRoute: typeof AdminLayoutAdminTestAddRoute
  AdminLayoutAdminTestChangeRoute: typeof AdminLayoutAdminTestChangeRoute
  AdminLayoutAdminBranchesIndexRoute: typeof AdminLayoutAdminBranchesIndexRoute
  AdminLayoutAdminMembersIndexRoute: typeof AdminLayoutAdminMembersIndexRoute
  AdminLayoutAdminNominationsIndexRoute: typeof AdminLayoutAdminNominationsIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAdminAnalyticRoute: AdminLayoutAdminAnalyticRoute,
  AdminLayoutAdminResultsRoute: AdminLayoutAdminResultsRoute,
  AdminLayoutAdminBranchesCreateBranchRoute:
    AdminLayoutAdminBranchesCreateBranchRoute,
  AdminLayoutAdminBranchesUpdateBranchRoute:
    AdminLayoutAdminBranchesUpdateBranchRoute,
  AdminLayoutAdminMembersCreateMemberRoute:
    AdminLayoutAdminMembersCreateMemberRoute,
  AdminLayoutAdminMembersUpdateMemberRoute:
    AdminLayoutAdminMembersUpdateMemberRoute,
  AdminLayoutAdminNominationsCreateNominationRoute:
    AdminLayoutAdminNominationsCreateNominationRoute,
  AdminLayoutAdminNominationsUpdateNominationRoute:
    AdminLayoutAdminNominationsUpdateNominationRoute,
  AdminLayoutAdminTestAddRoute: AdminLayoutAdminTestAddRoute,
  AdminLayoutAdminTestChangeRoute: AdminLayoutAdminTestChangeRoute,
  AdminLayoutAdminBranchesIndexRoute: AdminLayoutAdminBranchesIndexRoute,
  AdminLayoutAdminMembersIndexRoute: AdminLayoutAdminMembersIndexRoute,
  AdminLayoutAdminNominationsIndexRoute: AdminLayoutAdminNominationsIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface HeaderLayoutRouteChildren {
  HeaderLayoutAdminRoute: typeof HeaderLayoutAdminRoute
  HeaderLayoutIndexRoute: typeof HeaderLayoutIndexRoute
}

const HeaderLayoutRouteChildren: HeaderLayoutRouteChildren = {
  HeaderLayoutAdminRoute: HeaderLayoutAdminRoute,
  HeaderLayoutIndexRoute: HeaderLayoutIndexRoute,
}

const HeaderLayoutRouteWithChildren = HeaderLayoutRoute._addFileChildren(
  HeaderLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof HeaderLayoutRouteWithChildren
  '/admin': typeof HeaderLayoutAdminRoute
  '/': typeof HeaderLayoutIndexRoute
  '/admin/analytic': typeof AdminLayoutAdminAnalyticRoute
  '/admin/results': typeof AdminLayoutAdminResultsRoute
  '/admin/branches/create-branch': typeof AdminLayoutAdminBranchesCreateBranchRoute
  '/admin/branches/update-branch': typeof AdminLayoutAdminBranchesUpdateBranchRoute
  '/admin/members/create-member': typeof AdminLayoutAdminMembersCreateMemberRoute
  '/admin/members/update-member': typeof AdminLayoutAdminMembersUpdateMemberRoute
  '/admin/nominations/create-nomination': typeof AdminLayoutAdminNominationsCreateNominationRoute
  '/admin/nominations/update-nomination': typeof AdminLayoutAdminNominationsUpdateNominationRoute
  '/admin/test/add': typeof AdminLayoutAdminTestAddRoute
  '/admin/test/change': typeof AdminLayoutAdminTestChangeRoute
  '/admin/branches': typeof AdminLayoutAdminBranchesIndexRoute
  '/admin/members': typeof AdminLayoutAdminMembersIndexRoute
  '/admin/nominations': typeof AdminLayoutAdminNominationsIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AdminLayoutRouteWithChildren
  '/admin': typeof HeaderLayoutAdminRoute
  '/': typeof HeaderLayoutIndexRoute
  '/admin/analytic': typeof AdminLayoutAdminAnalyticRoute
  '/admin/results': typeof AdminLayoutAdminResultsRoute
  '/admin/branches/create-branch': typeof AdminLayoutAdminBranchesCreateBranchRoute
  '/admin/branches/update-branch': typeof AdminLayoutAdminBranchesUpdateBranchRoute
  '/admin/members/create-member': typeof AdminLayoutAdminMembersCreateMemberRoute
  '/admin/members/update-member': typeof AdminLayoutAdminMembersUpdateMemberRoute
  '/admin/nominations/create-nomination': typeof AdminLayoutAdminNominationsCreateNominationRoute
  '/admin/nominations/update-nomination': typeof AdminLayoutAdminNominationsUpdateNominationRoute
  '/admin/test/add': typeof AdminLayoutAdminTestAddRoute
  '/admin/test/change': typeof AdminLayoutAdminTestChangeRoute
  '/admin/branches': typeof AdminLayoutAdminBranchesIndexRoute
  '/admin/members': typeof AdminLayoutAdminMembersIndexRoute
  '/admin/nominations': typeof AdminLayoutAdminNominationsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_adminLayout': typeof AdminLayoutRouteWithChildren
  '/_headerLayout': typeof HeaderLayoutRouteWithChildren
  '/_headerLayout/admin': typeof HeaderLayoutAdminRoute
  '/_headerLayout/': typeof HeaderLayoutIndexRoute
  '/_adminLayout/admin/analytic': typeof AdminLayoutAdminAnalyticRoute
  '/_adminLayout/admin/results': typeof AdminLayoutAdminResultsRoute
  '/_adminLayout/admin/branches/create-branch': typeof AdminLayoutAdminBranchesCreateBranchRoute
  '/_adminLayout/admin/branches/update-branch': typeof AdminLayoutAdminBranchesUpdateBranchRoute
  '/_adminLayout/admin/members/create-member': typeof AdminLayoutAdminMembersCreateMemberRoute
  '/_adminLayout/admin/members/update-member': typeof AdminLayoutAdminMembersUpdateMemberRoute
  '/_adminLayout/admin/nominations/create-nomination': typeof AdminLayoutAdminNominationsCreateNominationRoute
  '/_adminLayout/admin/nominations/update-nomination': typeof AdminLayoutAdminNominationsUpdateNominationRoute
  '/_adminLayout/admin/test/add': typeof AdminLayoutAdminTestAddRoute
  '/_adminLayout/admin/test/change': typeof AdminLayoutAdminTestChangeRoute
  '/_adminLayout/admin/branches/': typeof AdminLayoutAdminBranchesIndexRoute
  '/_adminLayout/admin/members/': typeof AdminLayoutAdminMembersIndexRoute
  '/_adminLayout/admin/nominations/': typeof AdminLayoutAdminNominationsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/'
    | '/admin/analytic'
    | '/admin/results'
    | '/admin/branches/create-branch'
    | '/admin/branches/update-branch'
    | '/admin/members/create-member'
    | '/admin/members/update-member'
    | '/admin/nominations/create-nomination'
    | '/admin/nominations/update-nomination'
    | '/admin/test/add'
    | '/admin/test/change'
    | '/admin/branches'
    | '/admin/members'
    | '/admin/nominations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/admin'
    | '/'
    | '/admin/analytic'
    | '/admin/results'
    | '/admin/branches/create-branch'
    | '/admin/branches/update-branch'
    | '/admin/members/create-member'
    | '/admin/members/update-member'
    | '/admin/nominations/create-nomination'
    | '/admin/nominations/update-nomination'
    | '/admin/test/add'
    | '/admin/test/change'
    | '/admin/branches'
    | '/admin/members'
    | '/admin/nominations'
  id:
    | '__root__'
    | '/_adminLayout'
    | '/_headerLayout'
    | '/_headerLayout/admin'
    | '/_headerLayout/'
    | '/_adminLayout/admin/analytic'
    | '/_adminLayout/admin/results'
    | '/_adminLayout/admin/branches/create-branch'
    | '/_adminLayout/admin/branches/update-branch'
    | '/_adminLayout/admin/members/create-member'
    | '/_adminLayout/admin/members/update-member'
    | '/_adminLayout/admin/nominations/create-nomination'
    | '/_adminLayout/admin/nominations/update-nomination'
    | '/_adminLayout/admin/test/add'
    | '/_adminLayout/admin/test/change'
    | '/_adminLayout/admin/branches/'
    | '/_adminLayout/admin/members/'
    | '/_adminLayout/admin/nominations/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  HeaderLayoutRoute: typeof HeaderLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  HeaderLayoutRoute: HeaderLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_adminLayout",
        "/_headerLayout"
      ]
    },
    "/_adminLayout": {
      "filePath": "_adminLayout.tsx",
      "children": [
        "/_adminLayout/admin/analytic",
        "/_adminLayout/admin/results",
        "/_adminLayout/admin/branches/create-branch",
        "/_adminLayout/admin/branches/update-branch",
        "/_adminLayout/admin/members/create-member",
        "/_adminLayout/admin/members/update-member",
        "/_adminLayout/admin/nominations/create-nomination",
        "/_adminLayout/admin/nominations/update-nomination",
        "/_adminLayout/admin/test/add",
        "/_adminLayout/admin/test/change",
        "/_adminLayout/admin/branches/",
        "/_adminLayout/admin/members/",
        "/_adminLayout/admin/nominations/"
      ]
    },
    "/_headerLayout": {
      "filePath": "_headerLayout.tsx",
      "children": [
        "/_headerLayout/admin",
        "/_headerLayout/"
      ]
    },
    "/_headerLayout/admin": {
      "filePath": "_headerLayout/admin.tsx",
      "parent": "/_headerLayout"
    },
    "/_headerLayout/": {
      "filePath": "_headerLayout/index.tsx",
      "parent": "/_headerLayout"
    },
    "/_adminLayout/admin/analytic": {
      "filePath": "_adminLayout/admin/analytic.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/results": {
      "filePath": "_adminLayout/admin/results.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/branches/create-branch": {
      "filePath": "_adminLayout/admin/branches/create-branch.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/branches/update-branch": {
      "filePath": "_adminLayout/admin/branches/update-branch.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/members/create-member": {
      "filePath": "_adminLayout/admin/members/create-member.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/members/update-member": {
      "filePath": "_adminLayout/admin/members/update-member.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/nominations/create-nomination": {
      "filePath": "_adminLayout/admin/nominations/create-nomination.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/nominations/update-nomination": {
      "filePath": "_adminLayout/admin/nominations/update-nomination.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/test/add": {
      "filePath": "_adminLayout/admin/test/add.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/test/change": {
      "filePath": "_adminLayout/admin/test/change.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/branches/": {
      "filePath": "_adminLayout/admin/branches/index.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/members/": {
      "filePath": "_adminLayout/admin/members/index.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/nominations/": {
      "filePath": "_adminLayout/admin/nominations/index.tsx",
      "parent": "/_adminLayout"
    }
  }
}
ROUTE_MANIFEST_END */
