/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as HeaderLayoutImport } from './app/routes/_headerLayout'
import { Route as AdminLayoutImport } from './app/routes/_adminLayout'
import { Route as HeaderLayoutIndexImport } from './app/routes/_headerLayout/index'
import { Route as HeaderLayoutAdminImport } from './app/routes/_headerLayout/admin'
import { Route as AdminLayoutAdminNominationsImport } from './app/routes/_adminLayout/admin/nominations'
import { Route as AdminLayoutAdminAnalyticImport } from './app/routes/_adminLayout/admin/analytic'
import { Route as AdminLayoutAdminNominationsImport } from './app/routes/_adminLayout/admin/nominations'
import { Route as AdminLayoutAdminAdminAnalyticImport } f./app/routes/_adminLayout/admin/admin.analyticin.analytic'

// Create/Update Routes

const HeaderLayoutRoute = HeaderLayoutImport.update({
  id: '/_headerLayout',
  getParentRoute: () => rootRoute,
} as any)

const AdminLayoutRoute = AdminLayoutImport.update({
  id: '/_adminLayout',
  getParentRoute: () => rootRoute,
} as any)

const HeaderLayoutIndexRoute = HeaderLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeaderLayoutRoute,
} as any)

const HeaderLayoutAdminRoute = HeaderLayoutAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => HeaderLayoutRoute,
} as any)

const AdminLayoutAdminNominationsRoute =
  AdminLayoutAdminNominationsImport.update({
    id: '/admin/nominations',
    path: '/admin/nominations',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminNominationsRoute =
  AdminLayoutAdminNominationsImport.update({
    id: '/admin/nominations',
    path: '/admin/nominations',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

const AdminLayoutAdminAdminAnalyticRoute =
  AdminLayoutAdminAdminAnalyticImport.update({
    id: '/admin/admin/analytic',
    path: '/admin/admin/analytic',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_adminLayout': {
      id: '/_adminLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_headerLayout': {
      id: '/_headerLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HeaderLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_headerLayout/admin': {
      id: '/_headerLayout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof HeaderLayoutAdminImport
      parentRoute: typeof HeaderLayoutImport
    }
    '/_headerLayout/': {
      id: '/_headerLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutIndexImport
      parentRoute: typeof HeaderLayoutImport
    }
    '/_adminLayout/admin/nominations': {
      id: '/_adminLayout/admin/nominations'
      path: '/admin/nominations'
      fullPath: '/admin/nominations'
      preLoaderRoute: typeof AdminLayoutAdminNominationsImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/admin/analytic': {
      id: '/_adminLayout/admin/admin/analytic'
      path: '/admin/admin/analytic'
      fullPath: '/admin/admin/analytic'
      preLoaderRoute: typeof AdminLayoutAdminAdminAnalyticImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_adminLayout/admin/nominations': {
      id: '/_adminLayout/admin/nominations'
      path: '/admin/nominations'
      fullPath: '/admin/nominations'
      preLoaderRoute: typeof AdminLayoutAdminNominationsImport
      parentRoute: typeof AdminLayoutImport
    }
  }
}

// Create and export the route tree

interface AdminLayoutRouteChildren {
  AdminLayoutAdminAnalyticRoute: typeof AdminLayoutAdminAnalyticRoute
  AdminLayoutAdminNominationsRoute: typeof AdminLayoutAdminNominationsRoute
  AdminLayoutAdminNominationsRoute: typeof AdminLayoutAdminNominationsRoute
  AdminLayoutAdminAdminAnalyticRoute: typeof AdminLayoutAdminAdminAnalyticRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAdminAnalyticRoute: AdminLayoutAdminAnalyticRoute,
  AdminLayoutAdminNominationsRoute: AdminLayoutAdminNominationsRoute,
  AdminLayoutAdminNominationsRoute: AdminLayoutAdminNominationsRoute,
  AdminLayoutAdminAdminAnalyticRoute: AdminLayoutAdminAdminAnalyticRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface HeaderLayoutRouteChildren {
  HeaderLayoutAdminRoute: typeof HeaderLayoutAdminRoute
  HeaderLayoutIndexRoute: typeof HeaderLayoutIndexRoute
}

const HeaderLayoutRouteChildren: HeaderLayoutRouteChildren = {
  HeaderLayoutAdminRoute: HeaderLayoutAdminRoute,
  HeaderLayoutIndexRoute: HeaderLayoutIndexRoute,
}

const HeaderLayoutRouteWithChildren = HeaderLayoutRoute._addFileChildren(
  HeaderLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof HeaderLayoutRouteWithChildren
  '/admin': typeof HeaderLayoutAdminRoute
  '/': typeof HeaderLayoutIndexRoute
  '/admin/analytic': typeof AdminLayoutAdminAnalyticRoute
  '/admin/nominations': typeof AdminLayoutAdminNominationsRoute
  '/admin/nominations': typeof AdminLayoutAdminNominationsRoute
  '/admin/admin/analytic': typeof AdminLayoutAdminAdminAnalyticRoute
}

export interface FileRoutesByTo {
  '': typeof AdminLayoutRouteWithChildren
  '/admin': typeof HeaderLayoutAdminRoute
  '/': typeof HeaderLayoutIndexRoute
  '/admin/analytic': typeof AdminLayoutAdminAnalyticRoute
  '/admin/nominations': typeof AdminLayoutAdminNominationsRoute
  '/admin/nominations': typeof AdminLayoutAdminNominationsRoute
  '/admin/admin/analytic': typeof AdminLayoutAdminAdminAnalyticRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_adminLayout': typeof AdminLayoutRouteWithChildren
  '/_headerLayout': typeof HeaderLayoutRouteWithChildren
  '/_headerLayout/admin': typeof HeaderLayoutAdminRoute
  '/_headerLayout/': typeof HeaderLayoutIndexRoute
  '/_adminLayout/admin/analytic': typeof AdminLayoutAdminAnalyticRoute
  '/_adminLayout/admin/nominations': typeof AdminLayoutAdminNominationsRoute
  '/_adminLayout/admin/nominations': typeof AdminLayoutAdminNominationsRoute
  '/_adminLayout/admin/admin/analytic': typeof AdminLayoutAdminAdminAnalyticRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/admin' | '/' | '/admin/analytic' | '/admin/nominations'
  fullPaths:
    | ''
    | '/admin'
    | '/'
    | '/admin/nominations'
    | '/admin/admin/analytic'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/admin' | '/' | '/admin/analytic' | '/admin/nominations'
  to: '' | '/admin' | '/' | '/admin/nominations' | '/admin/admin/analytic'
  id:
    | '__root__'
    | '/_adminLayout'
    | '/_headerLayout'
    | '/_headerLayout/admin'
    | '/_headerLayout/'
    | '/_adminLayout/admin/analytic'
    | '/_adminLayout/admin/nominations'
    | '/_adminLayout/admin/nominations'
    | '/_adminLayout/admin/admin/analytic'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  HeaderLayoutRoute: typeof HeaderLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  HeaderLayoutRoute: HeaderLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_adminLayout",
        "/_headerLayout"
      ]
    },
    "/_adminLayout": {
      "filePath": "_adminLayout.tsx",
      "children": [
        "/_adminLayout/admin/analytic",
        "/_adminLayout/admin/nominations"
        "/_adminLayout/admin/nominations",
        "/_adminLayout/admin/admin/analytic"
      ]
    },
    "/_headerLayout": {
      "filePath": "_headerLayout.tsx",
      "children": [
        "/_headerLayout/admin",
        "/_headerLayout/"
      ]
    },
    "/_headerLayout/admin": {
      "filePath": "_headerLayout/admin.tsx",
      "parent": "/_headerLayout"
    },
    "/_headerLayout/": {
      "filePath": "_headerLayout/index.tsx",
      "parent": "/_headerLayout"
    },
    "/_adminLayout/admin/analytic": {
      "filePath": "_adminLayout/admin/analytic.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/nominations": {
      "filePath": "_adminLayout/admin/nominations.tsx",
    "/_adminLayout/admin/nominations": {
      "filePath": "_adminLayout/admin.nominations.tsx",
      "parent": "/_adminLayout"
    },
    "/_adminLayout/admin/admin/analytic": {
      "filePath": "_adminLayout/admin/admin.analytic.tsx",
      "parent": "/_adminLayout"
    }
  }
}
ROUTE_MANIFEST_END */
